# Generated by Django 3.2 on 2022-10-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='food_item',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='wine_item',
            new_name='wine',
        ),
    ]
