# Generated by Django 3.2 on 2022-10-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20221007_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='food_quantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='wine',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='wine_quantity',
        ),
    ]
