# Generated by Django 3.2 on 2022-09-10 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_friendly_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencetype',
            old_name='exp_name',
            new_name='name',
        ),
    ]
