# Generated by Django 3.2 on 2022-09-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_exp_name_experiencetype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='experiencetype',
            options={'verbose_name': 'Experience Type'},
        ),
        migrations.AddField(
            model_name='food',
            name='product_type',
            field=models.CharField(default='Food', max_length=255),
        ),
        migrations.AddField(
            model_name='wine',
            name='product_type',
            field=models.CharField(default='Wine', max_length=255),
        ),
    ]
