# Generated by Django 3.2 on 2022-09-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220912_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='slug',
            field=models.SlugField(default='food', max_length=255),
        ),
        migrations.AddField(
            model_name='wine',
            name='slug',
            field=models.SlugField(default='wine', max_length=255),
        ),
    ]
