# Generated by Django 3.2 on 2022-11-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_pairing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pairing',
            old_name='wine',
            new_name='name',
        ),
    ]
