# Generated by Django 3.2 on 2022-11-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_wine_pairing_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairing',
            name='main',
        ),
        migrations.RemoveField(
            model_name='pairing',
            name='recipes',
        ),
        migrations.AddField(
            model_name='pairing',
            name='food',
            field=models.ManyToManyField(to='products.Food'),
        ),
    ]
