# Generated by Django 3.2 on 2022-11-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20221109_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='pairing',
            field=models.ManyToManyField(related_name='pairing', to='products.Pairing'),
        ),
    ]
